### ISSUE TITLE
Create newsletter HTML templates to integrate to the Backend

### ISSUE THREAD

**Issue by cdparra** [socialappslab/appcivist-patterns#132] opened 2017-08-08 21:40 UTC
**Campaign without Activity**

![image](https://user-images.githubusercontent.com/630150/29095868-78e17ad8-7c60-11e7-9c11-705dd11bdf88.png)

**Campaign in Idea Collection Stage**
![image](https://user-images.githubusercontent.com/630150/29095872-7b30302c-7c60-11e7-85de-02e9ca176bc8.png)

**Campaign in Proposal Stage**
![image](https://user-images.githubusercontent.com/630150/29095901-9202f7b2-7c60-11e7-99bd-20bb4703995d.png)

**Campaign No rich text format**
![image](https://user-images.githubusercontent.com/630150/29095910-9ab56304-7c60-11e7-85da-0aa66ad38d6e.png)

**Comment by gvescu** [comment] 2017-08-19 14:00
This issue seems like a duplicate of #116, #117 and #118 @cdparra

**Closed as completed** 2017-08-23 12:23 UTC
Labels: duplicate
